apiVersion: v1
kind: Service
metadata:
 name: eurekaserver
 labels:
  app: eurekaserver
spec:
 type: NodePort
 ports:
 - port: 8761
   targetPort: 8761
   nodePort: 30000
 selector:
   client: eurekaserver 
 
