apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
 labels:
  tier: database
spec:
 containers: 
  - name: mysql-container
    image: mysql:5.7
    env:
     - name: MYSQL_USER
       value: root
     - name: MYSQL_ROOT_PASSWORD
       value: Mind@India#19   
    ports:
     - containerPort: 3306
