apiVersion: v1
kind: Service
metadata:
 name: ratings-data-service
 labels:
  app: ratings-data-service
spec:
# type: LoadBalancer
 ports:
 - port: 8082
   targetPort: 8082
 selector:
  type: ratings-data-service
