apiVersion: v1
kind: Pod
metadata:
 name: ratings-data-service
 labels:
  type: ratings-data-service
spec:
 containers: 
  - name: ratings-data-service
    image: krsai01/rating-service:11
    ports:
     - containerPort: 8082
    env:
     - name: mysqlservice
       value: mysql-service
