apiVersion: v1
kind: Service
metadata:
 name: movie-catalog-service
 labels:
  app: movie-catalog-service
spec:
 type: NodePort
 ports:
 - port: 8083
   targetPort: 8083
   nodePort: 30003
 selector:
  type: movie-catalog-service
