apiVersion: v1
kind: Pod
metadata:
 name: movie-info-service
 labels:
  type: movie-info-service
spec:
 containers: 
  - name: movie-info-service
    image: krsai01/movie-service:v12
    ports:
     - containerPort: 8081
    env:
     - name: mysqlservice
       value: mysql-service
     
